# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PikXbAEvkhPZpN3JPZmAtRevoSQAoYlU
"""

print ("Hellow World")

x = 14
y = 28
result = x + y
print(result)

str1 = "one two three four five six seven eight"
print(str1[8:18])
print(str1[-5:])

def plex(n=0):
    plex_value = "1" + "0"*n
    print(f'The plex of {n} is {plex_value}.')
    return int(plex_value)

sample_values = [3, 9, 25]

for n in sample_values:
    result = plex(n)